"""Nuclear War environment package."""

from .cards import (
    Card,
    CardCategory,
    build_deck,
    count_by_category,
    filter_by_category,
    load_card_definitions,
    shuffle_deck,
)
from .config import DEFAULT_CONFIG, AppConfig
from .constants import DEFAULT_LIMITS, Phase0Limits, V1Limits
from .engine import (
    DrawLimitReached,
    EngineEvent,
    advance_queue,
    declare_target,
    draw_phase,
    execute_launches,
    set_face_down_cards,
)
from .factory import (
    Phase0AECEnv,
    Phase0ParallelEnv,
    PostalParallelEnv,
    TableAECEnv,
    create_aec_env,
    create_parallel_env,
    create_phase0_aec_env,
    create_phase0_parallel_env,
    create_postal_env,
    create_table_env,
)
from .fallout import (
    FalloutOutcome,
    SpinnerEffect,
    resolve_spinner,
    roll_nuke_die,
    spin_spinner,
)
from .rng import SeededRNG
from .state import (
    DETERRENT_SLOTS,
    FACE_DOWN_SLOTS,
    HAND_LIMIT,
    GameState,
    PlayerState,
    Ruleset,
    create_players,
    distribute_population,
)

__all__ = [
    "AppConfig",
    "DEFAULT_CONFIG",
    "DEFAULT_LIMITS",
    "Phase0Limits",
    "V1Limits",
    "Phase0AECEnv",
    "Phase0ParallelEnv",
    "TableAECEnv",
    "PostalParallelEnv",
    "create_aec_env",
    "create_parallel_env",
    "create_phase0_aec_env",
    "create_phase0_parallel_env",
    "create_table_env",
    "create_postal_env",
    "Card",
    "CardCategory",
    "build_deck",
    "shuffle_deck",
    "filter_by_category",
    "count_by_category",
    "load_card_definitions",
    "SeededRNG",
    "Ruleset",
    "GameState",
    "PlayerState",
    "create_players",
    "distribute_population",
    "HAND_LIMIT",
    "FACE_DOWN_SLOTS",
    "DETERRENT_SLOTS",
    "SpinnerEffect",
    "FalloutOutcome",
    "resolve_spinner",
    "spin_spinner",
    "roll_nuke_die",
    "EngineEvent",
    "DrawLimitReached",
    "draw_phase",
    "advance_queue",
    "set_face_down_cards",
    "declare_target",
    "execute_launches",
]
